[package]
name = "iced_wgpu"
version = "0.2.2"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A wgpu renderer for Iced"
license = "MIT AND OFL-1.1"
repository = "https://github.com/hecrj/iced"

[features]
svg = ["resvg"]
canvas = ["iced_graphics/canvas"]
default_system_font = ["iced_graphics/font-source"]

[dependencies]
# wgpu = "0.5"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "554327a3d5bf596c9ca9514db5522287e69b9c18" }
# wgpu_glyph = "0.9"
wgpu_glyph = { git = "https://github.com/lachlansneff/wgpu_glyph.git", rev = "e150006fb1248bce565eb8e29f8c4747ed91ebb9" }

glyph_brush = "0.7"
zerocopy = "0.3"
bytemuck = "1.2"
raw-window-handle = "0.3"
glam = "0.8"
log = "0.4"
guillotiere = "0.5"
# Pin `gfx-memory` until https://github.com/gfx-rs/wgpu-rs/issues/261 is
# resolved
gfx-memory = "=0.1.1"

[dependencies.iced_native]
version = "0.2"
path = "../native"

[dependencies.iced_graphics]
version = "0.1"
path = "../graphics"
features = ["font-fallback", "font-icons"]

[dependencies.image]
version = "0.23"
optional = true

[dependencies.resvg]
version = "0.9"
features = ["raqote-backend"]
optional = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
